title: adiii.me
description: Chillin'
baseurl: "" 
url: "https://adiii.me"

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag


exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

include:
  - .well-known
